# Generated by Django 4.2 on 2024-09-26 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_ingredient_origin_size_alter_evaluation_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='name',
            new_name='size',
        ),
    ]
