# Generated by Django 4.2 on 2024-09-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_remove_evaluation_image_evaluationimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='evaluationimage',
            table=None,
        ),
    ]
