# Generated by Django 4.2 on 2024-10-14 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="like_count",
            field=models.IntegerField(default=0),
        ),
    ]
