# Generated by Django 4.2 on 2024-10-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_alter_community_like_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="like_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
