# Generated by Django 5.1.2 on 2024-10-14 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_followings'),
        ('accounts', '0002_user_points'),
    ]

    operations = [
    ]
