# Generated by Django 4.2 on 2024-09-26 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_test"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="test",
        ),
    ]
