# Generated by Django 4.2 on 2024-09-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_birth"),
        ("accounts", "0005_remove_user_test"),
    ]

    operations = []
