# Generated by Django 4.2 on 2024-10-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
    ]
