# Generated by Django 4.2 on 2024-10-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_order_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="price",
            new_name="total_price",
        ),
    ]
